# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
 title: Research Blog
email: me@me.com
description: Notebooks from my computing research
baseurl: "/research"  # the subpath of your site, e.g. /blog
url: "http://pauljean.github.io" # the base hostname & protocol for your site
twitter_username: @rule146
github_username: paul-jean

# Build settings
markdown: kramdown
highlighter: rouge
